# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  job1:
    runs-on: windows-latest
    # Map a step output to a job output
    outputs:
      output1: ${{ steps.step1.outputs.new-commits }}
      output2: ${{ steps.step2.outputs.changed-files }}
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3
        with:
          ref: 'main'
          fetch-depth: 0

      - name: Check for new commits in 2 hours
        id: new-commits
        uses: adriangl/check-new-commits-action@v1.0.3
        with:
          seconds: 7200
          branch: 'main'

      - name: Get specific changed files
        if: steps.new-commits.outputs.has-new-commits == 'true'
        id: changed-files
        uses: tj-actions/changed-files@v29.0.7
        with:
          files_ignore: |
            *.yml
      - id: step1
        run: echo "new-commits=hello" >> $GITHUB_OUTPUT
      - id: step2
        run: echo "changed-files=world" >> $GITHUB_OUTPUT
  job2:
    runs-on: windows-latest
    needs: job1
    if: needs.job1.outputs.output1 == 'hello'
    steps:
      - run: echo ${{needs.job1.outputs.output1}} ${{needs.job1.outputs.output2}}
